# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Bm0-mwEbf1p1iQr-esHhGETXLRvO6VK
"""

import pandas as pd
teacher= pd.DataFrame({
    'FISH': ['Xalilov D.A'],
    'Kafedrasi': ['Axborot Texnologiyalari'],
    'Fani': ['Sun`iy Intellekt Asoslari'],
    'Mustaqil ta`lim soati': ['108 soat']
})
print(teacher)

teacher.to_excel('teacher.xlsx', index=False, sheet_name='Sheet1')